---
title: "Previsão Importações Total Brasil"
author: "Pedro Pablo Skorin"
date: "17/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
source('..\\R\\functions.R')

#### Entrada de dados ####

theme = '_imp'
title_gg = 'Importações Total Brasil'
y_axis = 'Log das Importações (US$)'

X = read_csv('..\\X.csv', col_names = T, progress = T)[,-c(1,2)]
Y_or = read.csv(paste('Y_or', theme, '.csv',sep = ''))[,3]
date = as.Date(read.csv(paste('Y_or', theme, '.csv',sep = ''))[,1])
Y = read.csv(paste('Y_or', theme, '.csv',sep = ''))[-1,4]

X_lag = add_lags(X,Y)
Y_lag = tail(Y,-11)
Y_or_lag = tail(Y_or,-11)
names = colnames(X_lag)
colnames(X_lag) = 1:(ncol(X_lag))

#### Pré-processamento ####

ratio_start_in = .757
ratio_start_lag = 0.75

n_tot_lag <- length(Y_lag)
n_out_lag <- ceiling(n_tot_lag - ratio_start_lag*n_tot_lag)
ind_out_lag <- seq(to = n_tot_lag, by = 1, length = n_out_lag)

n_tot <- length(Y)
n_out <- ceiling(n_tot - ratio_start_in*n_tot)
ind_out <- seq(to = n_tot, by = 1, length = n_out)

```

## Previsão de Séries Temporais

Neste documento avaliamos diferentes modelos para a previsão das Importações do Brasil da China.

### Gráfico da Série com Corte para Início da Previsão

```{r plot_central, echo=FALSE}
df_y = data.frame(Date = date,Y = Y_or)

ggplot(df_y, aes(Date, Y)) +
  geom_line(size = 0.2, color = 'black') +
  geom_vline(xintercept = date[floor((length(Y_or)-1)*ratio_start_in)],
             linetype="dashed",
             color = "red", size=0.6)  + 
  labs(title=title_gg,
       x ="Data", y = y_axis)
```

### Previsão em Diferentes Horizontes

#### h=1

```{r h1, echo=FALSE}
sarima_1 = readRDS(paste('objects\\sarima_1', theme, '.RData', sep = ''))
lasso_1 = readRDS(paste('objects\\lasso_1', theme, '.RData', sep = ''))
ridge_1 = readRDS(paste('objects\\ridge_1', theme, '.RData', sep = ''))
elast_1 = readRDS(paste('objects\\elast_1', theme, '.RData', sep = ''))
boost_1 = readRDS(paste('objects\\boost_1', theme, '.RData', sep = ''))

df_forecast_1 = data.frame(Date = tail(date,74), Y = tail(Y_or,74),
                           sarima = sarima_1$benchmark,
                           lasso = lasso_1$forecast, ridge = ridge_1$forecast,
                           boost = boost_1$forecast, elast = elast_1$forecast)

ggplot(df_forecast_1, aes(Date)) +
  geom_line(aes(y = Y, colour = "Y"), size = 0.7, color = 'black') + 
  geom_line(aes(y = sarima, colour = "SARIMA")) +
  geom_line(aes(y = lasso, colour = 'lasso')) +
  geom_line(aes(y = ridge, colour = 'ridge')) +
  geom_line(aes(y = boost, colour = 'boost')) +
  geom_line(aes(y = elast, colour = 'elast')) + 
  labs(title=paste("Previsão", title_gg,'com h = 1', sep = ' '),
       x ="Data", y = y_axis,
       colour = 'Modelo')
```

```{r h1_e, echo=TRUE}
sarima_e_1 = evaluation(sarima_1$benchmark, Y_or, ind_out, "sarima h=1")
lasso_e_1 = evaluation(lasso_1$forecast, Y_or_lag, ind_out_lag, "lasso h=1")
ridge_e_1 = evaluation(ridge_1$forecast, Y_or_lag, ind_out_lag, "ridge h=1")
elast_e_1 = evaluation(elast_1$forecast, Y_or_lag, ind_out_lag, "elast h=1")
boost_e_1 = evaluation(boost_1$forecast, Y_or_lag, ind_out_lag, "boost h=1")
```


#### h=2

```{r h2, echo=FALSE}
sarima_2 = readRDS(paste('objects\\sarima_2', theme, '.RData', sep = ''))
lasso_2 = readRDS(paste('objects\\lasso_2', theme, '.RData', sep = ''))
ridge_2 = readRDS(paste('objects\\ridge_2', theme, '.RData', sep = ''))
elast_2 = readRDS(paste('objects\\elast_2', theme, '.RData', sep = ''))
boost_2 = readRDS(paste('objects\\boost_2', theme, '.RData', sep = ''))

df_forecast_2 = data.frame(Date = tail(date,74), Y = tail(Y_or,74),
                           sarima = sarima_2$benchmark,
                           lasso = lasso_2$forecast, ridge = ridge_2$forecast,
                           boost = boost_2$forecast, elast = elast_2$forecast)

ggplot(df_forecast_2, aes(Date)) +
  geom_line(aes(y = Y, colour = "Y"), size = 0.7, color = 'black') + 
  geom_line(aes(y = sarima, colour = "SARIMA")) +
  geom_line(aes(y = lasso, colour = 'lasso')) +
  geom_line(aes(y = ridge, colour = 'ridge')) +
  geom_line(aes(y = boost, colour = 'boost')) +
  geom_line(aes(y = elast, colour = 'elast')) + 
  labs(title=paste("Previsão", title_gg,'com h = 2', sep = ' '),
       x ="Data", y = y_axis,
       colour = 'Modelo')
```

```{r h2_e, echo=TRUE}
sarima_e_2 = evaluation(sarima_2$benchmark, Y_or, ind_out, "sarima h=2")
lasso_e_2 = evaluation(lasso_2$forecast, Y_or_lag, ind_out_lag, "lasso h=2")
ridge_e_2 = evaluation(ridge_2$forecast, Y_or_lag, ind_out_lag, "ridge h=2")
elast_e_2 = evaluation(elast_2$forecast, Y_or_lag, ind_out_lag, "elast h=2")
boost_e_2 = evaluation(boost_2$forecast, Y_or_lag, ind_out_lag, "boost h=2")
```

#### h=3

```{r h3, echo=FALSE}
sarima_3 = readRDS(paste('objects\\sarima_3', theme, '.RData', sep = ''))
lasso_3 = readRDS(paste('objects\\lasso_3', theme, '.RData', sep = ''))
ridge_3 = readRDS(paste('objects\\ridge_3', theme, '.RData', sep = ''))
elast_3 = readRDS(paste('objects\\elast_3', theme, '.RData', sep = ''))
boost_3 = readRDS(paste('objects\\boost_3', theme, '.RData', sep = ''))

df_forecast_3 = data.frame(Date = tail(date,74), Y = tail(Y_or,74),
                           sarima = sarima_3$benchmark,
                           lasso = lasso_3$forecast, ridge = ridge_3$forecast,
                           boost = boost_3$forecast, elast = elast_3$forecast)

ggplot(df_forecast_3, aes(Date)) +
  geom_line(aes(y = Y, colour = "Y"), size = 0.7, color = 'black') + 
  geom_line(aes(y = sarima, colour = "SARIMA")) +
  geom_line(aes(y = lasso, colour = 'lasso')) +
  geom_line(aes(y = ridge, colour = 'ridge')) +
  geom_line(aes(y = boost, colour = 'boost')) +
  geom_line(aes(y = elast, colour = 'elast')) + 
  labs(title=paste("Previsão", title_gg,'com h = 3', sep = ' '),
       x ="Data", y = y_axis,
       colour = 'Modelo')
```

```{r h3_e, echo=TRUE}
sarima_e_3 = evaluation(sarima_3$benchmark, Y_or, ind_out, "sarima h=3")
lasso_e_3 = evaluation(lasso_3$forecast, Y_or_lag, ind_out_lag, "lasso h=3")
ridge_e_3 = evaluation(ridge_3$forecast, Y_or_lag, ind_out_lag, "ridge h=3")
elast_e_3 = evaluation(elast_3$forecast, Y_or_lag, ind_out_lag, "elast h=3")
boost_e_3 = evaluation(boost_3$forecast, Y_or_lag, ind_out_lag, "boost h=3")
```

